# ┌────────────────────────────────────────────────────────┐
# │                                                        │
# │                   칭호북 아이템 설정                      │
# │                                                        │
# └────────────────────────────────────────────────────────┘

#칭호 플러그인의 아이템을 설정 할 수 있는 부분입니다.
#prefix가 칭호입니다.

#칭호GUI 행 개수(기본값 : 3)
#1~6사이로만 설정 가능하며, 그 이상으로 설정할시 자동으로 3으로 설정합니다.
#이건 삭제GUI와 열기 GUI의 행 개수에 같이 적용됩니다.
gui_row: 3

#기본 칭호(서버에 처음 들어올때 적용되는 칭호, 빈칸일 시 칭호 없음)
default_prefix: ""

Title_book:
  type: BOOK
  name: "prefix"
  lore:
    - "&f우클릭으로 흭득가능합니다."

#칭호 GUI아이템 설정
Title_book_Icon:
  type: NAME_TAG
  name: "prefix"
  lore:
    - "&f클릭으로 장착 할 수 있습니다."

#선택한 GUI아이템 설정(Title_book_Icon의 타입과 이름을 따라갑니다)
Title_book_Icon_select:
  lore:
    - "&f이미 장착한 칭호입니다."
    - "&f쉬프트 클릭시 칭호를 장착 해제합니다."

#칭호 삭제아이콘 설정
Title_book_del:
  type: BOOK
  name: "prefix"
  lore:
    - "&f클릭으로 칭호를 삭제할 수 있습니다."





